"""Interactive workspace setup for AAP Bridge.

``aap-bridge init`` creates a self-contained working directory holding the
``.env``, ``config/config.yaml``, and artifact directories a migration needs.
It is the entry point for an installed, source-free CLI: nothing outside this
directory is written, and no repository checkout is required.

The installer scripts under ``scripts/`` call this command as their final step.
"""

from __future__ import annotations

import base64
import os
import re
import secrets
import shutil
from pathlib import Path
from urllib.parse import quote

import click

from aap_migration.cli import diagnostics, ui
from aap_migration.resources import SUPPORTED_SOURCE_VERSIONS, SUPPORTED_TARGET_VERSIONS

#: Directories a migration writes into, created inside the workspace.
_ARTIFACT_DIRS = ("exports", "xformed", "reports", "logs", "schemas", "backups")

#: Port the bundled compose PostgreSQL service publishes on the host. Every
#: published port is configurable, so a machine already running PostgreSQL on
#: the default does not have to give it up.
_DEFAULT_DB_PORT = 15432


def _bundled_db_port() -> int:
    """The host port for the bundled database, from the environment or default."""
    raw = os.environ.get("AAP_BRIDGE_DB_PORT", "")
    return int(raw) if raw.isdigit() else _DEFAULT_DB_PORT


_BUNDLED_DB_NAME = "aap_migration"
_BUNDLED_DB_USER = "aap_migration_user"

_CONFIG_TEMPLATE = """\
# AAP Bridge configuration
#
# Generated by `aap-bridge init`. Endpoints and tokens live in the sibling
# .env file; this file only references them.
#
# Every other setting (performance tuning, validation, logging, batch sizes)
# uses a built-in default. Add sections here only to override one. See:
# https://redhat-cop.github.io/aap-bridge/getting-started/configuration/

source:
  url: ${SOURCE__URL}
  version: ${SOURCE__VERSION}
  verify_ssl: ${SOURCE__VERIFY_SSL}
  timeout: ${SOURCE__TIMEOUT}

target:
  url: ${TARGET__URL}
  version: ${TARGET__VERSION}
  verify_ssl: ${TARGET__VERIFY_SSL}
  timeout: ${TARGET__TIMEOUT}

state:
  # Migration state database connection string, from .env
  db_path: ${MIGRATION_STATE_DB_PATH}
"""

# Only the database service. The CLI workflow needs somewhere to run PostgreSQL
# without shipping the whole application stack; the container installer
# overwrites this with the full engine + UI compose file.
_DB_COMPOSE_TEMPLATE = """\
# Bundled PostgreSQL for AAP Bridge migration state.
# Generated by `aap-bridge init`. Start it with: podman compose up -d db

services:
  db-init:
    image: registry.redhat.io/ubi9/ubi-minimal:latest
    user: "0"
    command:
      - /bin/sh
      - -ec
      - |
        mkdir -p /var/lib/pgsql/data
        chown -R 26:26 /var/lib/pgsql/data
        touch /tmp/ready
        exec sleep infinity
    volumes:
      - pgdata:/var/lib/pgsql/data
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/ready"]
      interval: 2s
      timeout: 2s
      retries: 10

  db:
    image: registry.redhat.io/rhel9/postgresql-15
    depends_on:
      db-init:
        condition: service_healthy
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER:?Set POSTGRESQL_USER in .env}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:?Set POSTGRESQL_PASSWORD in .env}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE:-aap_migration}
      POSTGRESQL_ADMIN_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD:?Set POSTGRESQL_ADMIN_PASSWORD in .env}
    ports:
      - "${AAP_BRIDGE_DB_PORT:-15432}:5432"
    volumes:
      - pgdata:/var/lib/pgsql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER:-aap_migration_user}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
"""


def _bundled_db_url(password: str) -> str:
    """Build the connection string for the bundled compose PostgreSQL service."""
    return (
        f"postgresql://{_BUNDLED_DB_USER}:{quote(password, safe='')}"
        f"@localhost:{_bundled_db_port()}/{_BUNDLED_DB_NAME}"
    )


def _render_env(values: dict[str, str]) -> str:
    """Render the workspace .env file.

    Only the settings a migration actually needs are written. Everything else
    falls back to the defaults declared on the configuration models, so this
    file stays short enough to read and edit by hand.
    """
    return f"""\
# AAP Bridge environment
#
# Generated by `aap-bridge init`. Run the CLI from this directory, or set
# AAP_BRIDGE_ENV to point at this file from elsewhere.
#
# This file contains API tokens. It is created with 0600 permissions -
# keep it out of version control.

AAP_BRIDGE_CONFIG=config/config.yaml
AAP_BRIDGE_LOG_LEVEL=INFO

# --- Ports published on this machine ---
# Change any that clash with something already running; compose, the Web UI's
# proxy, and the connection string below all read these.
AAP_BRIDGE_DB_PORT={values["db_port"]}
AAP_BRIDGE_API_PORT={values["api_port"]}
AAP_BRIDGE_UI_PORT={values["ui_port"]}

# --- Source AAP (migrating from; a read-only token is enough) ---
SOURCE__URL={values["source_url"]}
SOURCE__VERSION={values["source_version"]}
SOURCE__TOKEN={values["source_token"]}
SOURCE__VERIFY_SSL={values["source_verify_ssl"]}
SOURCE__TIMEOUT=30

# --- Target AAP (migrating to; needs a read/write admin token) ---
TARGET__URL={values["target_url"]}
TARGET__VERSION={values["target_version"]}
TARGET__TOKEN={values["target_token"]}
TARGET__VERIFY_SSL={values["target_verify_ssl"]}
TARGET__TIMEOUT=30

# --- Migration state database ---
MIGRATION_STATE_DB_PATH={values["db_url"]}
{values["db_extra"]}
# --- Web UI only: encrypts saved connection tokens at rest ---
AAP_BRIDGE_TOKEN_ENCRYPTION_KEY={values["encryption_key"]}
"""


#: Defaults chosen for the common case rather than the newest release: people
#: migrate *from* an older instance *to* a current one.
_DEFAULT_SOURCE_VERSION = "2.3"
_DEFAULT_TARGET_VERSION = "2.6"

#: Matches a plausible version number, so a typo can be told apart from a real
#: but unsupported release.
_VERSION_RE = re.compile(r"^\d+\.\d+$")


def _read_env(path: Path) -> dict[str, str]:
    """Read an existing workspace .env into a plain mapping.

    Reconfiguring should not mean retyping settings that are already right, so
    what is there becomes the defaults. Read from the file rather than the
    environment: ``--dir`` can point at a workspace other than the one whose
    .env this process happens to have loaded.
    """
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    for line in path.read_text(errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def _clean(value: str) -> str:
    """Strip whitespace and trailing shell artefacts from typed input.

    A trailing backslash is common when a line was continued by accident, and
    should not cost the user a re-read of the whole supported-version list.
    """
    return value.strip().rstrip("\\").strip()


def _prompt_version(versions: tuple[str, ...], default: str) -> str:
    """Ask for an AAP version, keeping the failure path quiet.

    Listing eleven versions inline drowns the question, and repeating the list
    on every typo makes the interaction noisy. A malformed entry gets a
    one-line retry; a well-formed but unsupported release gets the range.
    """
    while True:
        answer = _clean(click.prompt(f"  Version [{default}]", default=default, show_default=False))
        if answer in versions:
            return answer
        if _VERSION_RE.match(answer):
            ui.fail(f"AAP {answer} is not supported.")
            click.echo(f"    Supported versions: {versions[0]}-{versions[-1]}")
        else:
            ui.fail("Invalid version. Try again.")
        click.echo()


def _prompt_instance(
    role: str, versions: tuple[str, ...], current: dict[str, str] | None = None
) -> dict[str, str]:
    """Collect URL, version, token, and TLS preference for one AAP instance.

    ``current`` holds the settings already in the workspace, used as defaults
    so that reconfiguring one thing does not mean retyping the rest.
    """
    ui.heading(f"{role.capitalize()} AAP")

    current = current or {}
    prefix = role.upper()
    current_url = current.get(f"{prefix}__URL", "")
    current_version = current.get(f"{prefix}__VERSION", "")
    current_token = current.get(f"{prefix}__TOKEN", "")

    if role == "source":
        default_version = current_version or _DEFAULT_SOURCE_VERSION
        token_note = "read-only is sufficient"
    else:
        default_version = current_version or _DEFAULT_TARGET_VERSION
        token_note = "admin read/write required"

    if current_url:
        url = _clean(click.prompt("  URL", default=current_url, show_default=True))
    else:
        url = _clean(click.prompt("  URL", type=str))
    url = url.rstrip("/")
    if not url.startswith(("http://", "https://")):
        url = f"https://{url}"

    version = _prompt_version(versions, default_version)

    # Say the input is hidden: with no echo, a new user cannot tell the
    # difference between a password prompt and a frozen terminal. An existing
    # token is never displayed, only kept: Enter leaves it alone.
    if current_token:
        token = _clean(
            click.prompt(
                "  API token [keep existing]",
                default="",
                show_default=False,
                hide_input=True,
            )
        )
        token = token or current_token
    else:
        token = _clean(
            click.prompt(f"  API token ({token_note}, input hidden)", type=str, hide_input=True)
        )

    current_verify = current.get(f"{prefix}__VERIFY_SSL", "").lower()
    verify_default = current_verify != "false" if current_verify else True
    verify_ssl = click.confirm("  Verify TLS certificates?", default=verify_default)
    if not verify_ssl:
        # Worth surfacing: it weakens the connection for the whole migration.
        click.echo()
        ui.warn("TLS certificate verification disabled")

    return {
        f"{role}_url": url,
        f"{role}_version": version,
        f"{role}_token": token,
        f"{role}_verify_ssl": "true" if verify_ssl else "false",
    }


def _bundled_db_env(password: str) -> str:
    """Render the .env lines the compose database service reads."""
    return (
        "\n# Credentials for the bundled database service (managed for you)\n"
        f"POSTGRESQL_USER={_BUNDLED_DB_USER}\n"
        f"POSTGRESQL_PASSWORD={password}\n"
        f"POSTGRESQL_DATABASE={_BUNDLED_DB_NAME}\n"
        f"POSTGRESQL_ADMIN_PASSWORD={password}\n"
    )


def _redact_db_url(url: str) -> str:
    """Show a connection string without its password."""
    if "://" not in url or "@" not in url:
        return url
    scheme, _, rest = url.partition("://")
    creds, _, host = rest.rpartition("@")
    user, _, password = creds.partition(":")
    return f"{scheme}://{user}:{'*' * 6}@{host}" if password else url


def _prompt_database(workspace: Path, current_url: str = "") -> tuple[str, str, bool]:
    """Choose between the bundled container database and an existing one.

    Returns:
        tuple: (connection string, extra .env lines, bundled selected). The
        bundled option also emits the POSTGRESQL_* variables the compose
        database service needs.
    """
    ui.heading("Migration database")
    click.echo("  AAP Bridge uses PostgreSQL to track migration progress.")
    click.echo()

    # Reconfiguring connection settings is not a reason to move the database
    # the migration state already lives in, so keeping it is the default.
    if current_url:
        click.echo(f"  Currently: {_redact_db_url(current_url)}")
        click.echo()
        if click.confirm("  Keep this database?", default=True):
            return current_url, "", False
        click.echo()

    has_podman = shutil.which("podman") is not None

    if not has_podman:
        # Without a container runtime the bundled option cannot work, so do not
        # offer a choice that is guaranteed to fail.
        if diagnostics.in_container():
            ui.warn("This CLI is in a container, so it cannot manage a database itself.")
            click.echo("  If the surrounding stack provides one, re-run with --managed-db.")
        else:
            ui.warn("Podman is not available, so the bundled database cannot be used.")
        click.echo()
        click.echo("  Example: postgresql://user:password@host:5432/aap_migration")
        url = click.prompt("  Connection string", type=str).strip()
        return url, "", False

    click.echo("  1. Use bundled PostgreSQL")
    click.echo("     Recommended - AAP Bridge manages it with Podman")
    click.echo()
    click.echo("  2. Use existing PostgreSQL")
    click.echo("     Provide your own connection string")
    click.echo()

    choice = click.prompt(
        "  Choose", type=click.Choice(["1", "2"]), default="1", show_choices=False
    )

    if choice == "1":
        password = secrets.token_hex(16)
        (workspace / "compose.yml").write_text(_DB_COMPOSE_TEMPLATE)
        # The generated password lands in .env and is never needed by hand,
        # so it is not worth a line of the user's attention.
        return _bundled_db_url(password), _bundled_db_env(password), True

    click.echo()
    click.echo("  Example: postgresql://user:password@host:5432/aap_migration")
    url = click.prompt("  Connection string", type=str).strip()
    return url, "", False


def _verify(workspace: Path, values: dict[str, str], *, check_db: bool = True) -> bool:
    """Run the same checks doctor runs, so setup cannot claim a false success.

    An unreachable AAP is reported as a warning rather than a failure. The
    workspace is written correctly either way, and an instance that is powered
    off or still booting is a transient condition, not a broken setup. Doctor
    treats the same result as a failure, because there it is diagnosing a
    system the user expects to be live.

    ``check_db`` is off when the database belongs to a stack the caller starts
    after this command returns: probing it here could only report a service
    that is not up yet as broken.

    Returns True when nothing blocking failed.
    """
    ui.heading("Verifying your setup" if check_db else "Checking AAP connections")

    healthy = True

    db_checks = diagnostics.check_database(values["db_url"], workspace) if check_db else []
    for check in db_checks:
        if check.status == "ok":
            ui.ok(check.name)
        elif check.status == "warn":
            ui.warn(check.name)
        else:
            ui.fail(check.name)
            healthy = False

    # An instance that is powered off or still booting is transient, so it
    # warns. A rejected token is a wrong value in .env that will not fix
    # itself, so it fails.
    unreachable = False
    for role, label in (("source", "Source"), ("target", "Target")):
        check = diagnostics.check_aap(
            values[f"{role}_url"],
            values[f"{role}_token"],
            values[f"{role}_verify_ssl"] == "true",
            label,
        )
        if check.status == "ok":
            ui.ok(check.name)
        elif "rejected the token" in check.name:
            ui.fail(check.name)
            healthy = False
        else:
            ui.warn(check.name)
            unreachable = True

    if unreachable:
        click.echo()
        click.echo("  Your settings are saved. Re-check once the instances are up.")

    return healthy


def _write_file(path: Path, content: str, *, secret: bool = False) -> None:
    """Write a workspace file, restricting permissions when it holds secrets."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    if secret:
        path.chmod(0o600)


def _summary(workspace: Path, healthy: bool) -> None:
    """Final screen: where the workspace is, and how to start.

    The file listing that used to live here is inventory, not a next action;
    ``aap-bridge doctor`` reports it when it matters.
    """
    ui.heading("Setup complete")
    click.echo("  Workspace:")
    click.echo(f"    {workspace}")
    click.echo()
    click.echo("  Configuration and migration data are stored in this workspace.")

    # Setup stops here. Starting a migration moves real data between two AAP
    # instances, so it stays an explicit action rather than something an
    # installer does on the user's behalf.
    if healthy:
        ui.heading("Start your migration:")
        click.echo("  aap-bridge")
        ui.heading("Need help?")
        click.echo("  aap-bridge doctor")
    else:
        ui.heading("Before you start:")
        click.echo("  aap-bridge doctor")
    click.echo()


@click.command(name="init")
@click.option(
    "--dir",
    "workspace",
    type=click.Path(file_okay=False, path_type=Path),
    default=".",
    help="Workspace directory to create or populate (default: current directory)",
)
@click.option("--force", is_flag=True, help="Overwrite an existing .env and config")
@click.option(
    "--managed-db",
    is_flag=True,
    help="The caller runs PostgreSQL (container install): write its credentials only",
)
def init(workspace: Path, force: bool, managed_db: bool) -> None:
    """Set up a migration workspace interactively.

    Creates .env and config/config.yaml, starts the bundled database, and
    verifies that it and both AAP instances are reachable.
    """
    workspace = workspace.expanduser().resolve()
    env_path = workspace / ".env"
    config_path = workspace / "config" / "config.yaml"

    existing = [p for p in (env_path, config_path) if p.exists()]
    if existing and not force:
        ui.heading("Workspace already configured")
        for path in existing:
            ui.warn(f"Already exists: {path}")
        click.echo()
        click.echo("  Re-run with --force to update these settings, or choose")
        click.echo("  another --dir. Migration data is never deleted either way.")
        click.echo()
        raise SystemExit(1)

    workspace.mkdir(parents=True, exist_ok=True)

    ui.heading("Configure your migration")
    click.echo("  A few details are needed to connect to your source and target AAP.")
    click.echo("  You can change these later in .env or config/config.yaml.")

    # Reconfiguring uses what is already there as the defaults, so changing one
    # setting does not mean retyping the rest - and never reveals a token.
    current = _read_env(env_path) if force else {}

    values: dict[str, str] = {}
    values.update(_prompt_instance("source", SUPPORTED_SOURCE_VERSIONS, current))
    values.update(_prompt_instance("target", SUPPORTED_TARGET_VERSIONS, current))
    if managed_db:
        # The caller's stack already contains PostgreSQL, so there is no choice
        # to make and nothing to start here: only credentials to agree on.
        password = secrets.token_hex(16)
        values["db_url"] = _bundled_db_url(password)
        values["db_extra"] = _bundled_db_env(password)
        bundled = False
    else:
        values["db_url"], values["db_extra"], bundled = _prompt_database(
            workspace, current.get("MIGRATION_STATE_DB_PATH", "")
        )
    # Keep the existing key: it decrypts the connection tokens the Web UI has
    # already saved, and a new one would silently orphan them.
    # Recorded so a port can be changed later without hunting for where it was
    # decided; an existing workspace keeps whatever it already had.
    values["db_port"] = current.get("AAP_BRIDGE_DB_PORT") or str(_bundled_db_port())
    values["api_port"] = current.get("AAP_BRIDGE_API_PORT") or os.environ.get(
        "AAP_BRIDGE_API_PORT", "8000"
    )
    values["ui_port"] = current.get("AAP_BRIDGE_UI_PORT") or os.environ.get(
        "AAP_BRIDGE_UI_PORT", "8080"
    )

    values["encryption_key"] = current.get("AAP_BRIDGE_TOKEN_ENCRYPTION_KEY") or (
        base64.urlsafe_b64encode(os.urandom(32)).decode()
    )

    _write_file(env_path, _render_env(values), secret=True)
    _write_file(config_path, _CONFIG_TEMPLATE)
    for name in _ARTIFACT_DIRS:
        (workspace / name).mkdir(parents=True, exist_ok=True)

    if bundled:
        ui.heading("Setting up PostgreSQL")
        ui.ok("Database configured")
        if not diagnostics.start_database(workspace):
            ui.warn("PostgreSQL could not be started automatically")
        else:
            ui.step("Starting PostgreSQL")
            if diagnostics.wait_for_database(values["db_url"], workspace):
                ui.ok("PostgreSQL ready")
            else:
                ui.warn("PostgreSQL started but is not accepting connections yet")

    healthy = _verify(workspace, values, check_db=not managed_db)

    # With a managed database the caller still has services to start, so it
    # owns the closing screen: two "setup complete" endings in one run would
    # be one too many, and the first would be premature.
    if not managed_db:
        _summary(workspace, healthy)
