.PHONY: help install install-dev clean format lint typecheck test test-unit test-integration \
       test-performance test-cov check docs docs-serve \
       init-env setup version venv install-editable all \
       build up-dev down shell logs

.DEFAULT_GOAL := help

# ===========================================================================
#  Local development (runs on host, no containers needed)
# ===========================================================================

PYTHON := python3
PIP := uv pip
PYTEST := $(PYTHON) -m pytest
BLACK := $(PYTHON) -m black
ISORT := $(PYTHON) -m isort
RUFF := $(PYTHON) -m ruff
MYPY := $(PYTHON) -m mypy

SRC_DIR := src
TESTS_DIR := tests
DOCS_DIR := docs

help: ## Show this help message
	@echo "AAP Bridge - Development Commands"
	@echo ""
	@echo "  Local development (no containers):"
	@echo "    make setup                         # Complete dev setup"
	@echo "    make test                          # Run all tests"
	@echo "    make check                         # Format + lint + typecheck + test"
	@echo "    make docs-serve                    # Serve docs locally"
	@echo ""
	@echo "  Container CLI workflow (optional):"
	@echo "    podman login registry.redhat.io    # One-time Red Hat registry login"
	@echo "    make init-env                      # Create .env for shared config"
	@echo "    make build                         # Build the CLI container images"
	@echo "    make up-dev                        # Start db + bridge container"
	@echo "    make shell                         # Open a shell in the bridge container"
	@echo "    make down                          # Stop the running containers"
	@echo ""
	@echo "  All targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "    \033[36m%-28s\033[0m %s\n", $$1, $$2}'

venv: ## Create virtual environment with uv
	uv venv --seed --python 3.12

install: ## Install production dependencies
	$(PIP) install -r requirements.txt

install-dev: ## Install development dependencies
	$(PIP) install -r requirements-dev.txt
	$(PYTHON) -m pre_commit install

install-editable: ## Install package in editable mode
	$(PIP) install -e .

clean: ## Clean up generated files
	find . -type f -name '*.py[co]' -delete
	find . -type d -name '__pycache__' -delete
	find . -type d -name '*.egg-info' -exec rm -rf {} + 2>/dev/null || true
	rm -rf build dist .eggs htmlcov .coverage coverage.xml .pytest_cache .mypy_cache .ruff_cache
	rm -f migration_state.db*

format: ## Format code with black and isort
	$(BLACK) $(SRC_DIR) $(TESTS_DIR)
	$(ISORT) $(SRC_DIR) $(TESTS_DIR)

lint: ## Run linters (ruff)
	$(RUFF) check $(SRC_DIR) $(TESTS_DIR)

typecheck: ## Run type checking with mypy
	$(MYPY) $(SRC_DIR)

test: ## Run all tests
	$(PYTEST) $(TESTS_DIR)

test-unit: ## Run only unit tests
	$(PYTEST) $(TESTS_DIR)/unit -v

test-integration: ## Run only integration tests
	$(PYTEST) $(TESTS_DIR)/integration -v -m integration

test-performance: ## Run only performance tests
	$(PYTEST) $(TESTS_DIR)/performance -v -m performance

test-cov: ## Run tests with coverage report
	$(PYTEST) $(TESTS_DIR) --cov=$(SRC_DIR) --cov-report=html --cov-report=term

.PHONY: test-watch
test-watch: ## Run tests in watch mode
	$(PYTEST) $(TESTS_DIR) -f

check: format lint typecheck test ## Run all checks (format, lint, typecheck, test)

.PHONY: pre-commit
pre-commit: ## Run pre-commit hooks on all files
	$(PYTHON) -m pre_commit run --all-files

docs: ## Build documentation
	uv pip install -e ".[docs]"
	uv run mkdocs build

docs-serve: ## Serve documentation locally
	uv pip install -e ".[docs]"
	uv run mkdocs serve -a localhost:8001

.PHONY: run-example
run-example: ## Run example migration (requires config)
	$(PYTHON) -m aap_migration.cli migrate full --config config/config.yaml --dry-run

init-env: ## Initialize .env file from .env.example
	@if [ ! -f .env ]; then \
		db_password="$$( $(PYTHON) -c 'import secrets; print(secrets.token_hex(16))' )"; \
		cp .env.example .env; \
		{ \
			echo ""; \
			echo "# Container CLI workflow credentials (generated by make init-env)"; \
			echo "POSTGRESQL_USER=aap_migration_user"; \
			echo "POSTGRESQL_PASSWORD=$$db_password"; \
			echo "POSTGRESQL_DATABASE=aap_migration"; \
			echo "POSTGRESQL_ADMIN_PASSWORD=$$db_password"; \
		} >> .env; \
		echo ".env file created from .env.example"; \
		echo "Generated PostgreSQL credentials for the container CLI workflow"; \
		echo "Please edit .env with your actual configuration"; \
	else \
		echo ".env file already exists"; \
	fi

setup: install-dev install-editable init-env ## Complete development setup

version: ## Show current version
	@$(PYTHON) -c "from importlib.metadata import version; print(f'AAP Bridge v{version(\"aap-bridge\")}')" 2>/dev/null || echo "Package not installed"

all: check docs ## Run all checks and build docs

# ===========================================================================
#  Optional container CLI workflow (requires podman)
# ===========================================================================

COMPOSE          := podman compose
BRIDGE_SVC       := bridge
BRIDGE_IMAGE     := localhost/aap-bridge:latest
BRIDGE_DEV_IMAGE := localhost/aap-bridge-dev:latest

build: ## Build aap-bridge container image (base + dev)
	podman build -t $(BRIDGE_IMAGE) .
	podman build -t $(BRIDGE_DEV_IMAGE) -f Containerfile.dev .

up-dev: ## Start db + bridge (CLI dev container)
	$(COMPOSE) up -d db bridge

down: ## Stop all containers
	$(COMPOSE) down

shell: ## Shell into bridge container
	$(COMPOSE) exec $(BRIDGE_SVC) /bin/bash

logs: ## Tail all container logs
	$(COMPOSE) logs -f
