name: Deploy Docs
on:
  push:
    branches: [ main ]
    paths: [ "docs/**", "mkdocs.yml", ".github/workflows/docs.yml" ]
  pull_request:
    paths: [ "docs/**", "mkdocs.yml", ".github/workflows/docs.yml" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # needed for git-revision-date plugin if you use it
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip
      - run: pip install ".[docs]"
      - run: mkdocs build --strict
      - if: github.event_name == 'push'
        run: mkdocs gh-deploy --force
